-- GENERATED by examples/brownfield/midday/scripts/brownfield-midday-live-schema.py
-- DO NOT EDIT. Regenerate instead.
--
-- Every statement below is midday's own committed SQL, copied verbatim from
-- examples/brownfield/midday/schema.sql (itself a byte-for-byte concatenation of
-- packages/db/migrations/*.sql). Nothing here is rewritten or synthesized.
--
-- Load live_db/supabase_runtime.sql BEFORE this file: these statements reference base tables,
-- roles, and auth/private functions that midday does not commit in packages/db/migrations.

CREATE TYPE invoice_recurring_frequency AS ENUM (
  'weekly',
  'monthly_date',
  'monthly_weekday',
  'custom'
);

CREATE TYPE invoice_recurring_end_type AS ENUM (
  'never',
  'on_date',
  'after_count'
);

CREATE TYPE invoice_recurring_status AS ENUM (
  'active',
  'paused',
  'completed',
  'canceled'
);

CREATE TABLE IF NOT EXISTS invoice_recurring (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  frequency invoice_recurring_frequency NOT NULL,
  frequency_day INTEGER, -- 0-6 for weekly (day of week), 1-31 for monthly_date
  frequency_week INTEGER, -- 1-5 for monthly_weekday (e.g., 1st, 2nd Friday)
  frequency_interval INTEGER, -- For custom: every X days
  end_type invoice_recurring_end_type NOT NULL,
  end_date TIMESTAMPTZ,
  end_count INTEGER,
  status invoice_recurring_status DEFAULT 'active' NOT NULL,
  invoices_generated INTEGER DEFAULT 0 NOT NULL,
  consecutive_failures INTEGER DEFAULT 0 NOT NULL, -- Track failures for auto-pause
  next_scheduled_at TIMESTAMPTZ,
  last_generated_at TIMESTAMPTZ,
  timezone TEXT NOT NULL,
  due_date_offset INTEGER DEFAULT 30 NOT NULL,
  amount NUMERIC(10, 2),
  currency TEXT,
  line_items JSONB,
  template JSONB,
  payment_details JSONB,
  from_details JSONB,
  note_details JSONB,
  customer_name TEXT,
  vat NUMERIC(10, 2),
  tax NUMERIC(10, 2),
  discount NUMERIC(10, 2),
  subtotal NUMERIC(10, 2),
  top_block JSONB,
  bottom_block JSONB,
  template_id UUID REFERENCES invoice_templates(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS invoice_recurring_team_id_idx ON invoice_recurring(team_id);

CREATE INDEX IF NOT EXISTS invoice_recurring_next_scheduled_at_idx ON invoice_recurring(next_scheduled_at);

CREATE INDEX IF NOT EXISTS invoice_recurring_status_idx ON invoice_recurring(status);

CREATE INDEX IF NOT EXISTS invoice_recurring_active_scheduled_idx ON invoice_recurring(next_scheduled_at) WHERE status = 'active';

ALTER TABLE invoice_recurring ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Invoice recurring can be handled by a member of the team"
  ON invoice_recurring
  FOR ALL
  TO public
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

ALTER TABLE invoice_recurring 
  ADD COLUMN IF NOT EXISTS upcoming_notification_sent_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS invoice_recurring_upcoming_notification_idx 
  ON invoice_recurring(next_scheduled_at, upcoming_notification_sent_at) 
  WHERE status = 'active';

CREATE TYPE insight_period_type AS ENUM ('weekly', 'monthly', 'quarterly', 'yearly');

CREATE TYPE insight_status AS ENUM ('pending', 'generating', 'completed', 'failed');

CREATE TABLE insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    
    period_type insight_period_type NOT NULL,
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP WITH TIME ZONE NOT NULL,
    period_year SMALLINT NOT NULL,
    period_number SMALLINT NOT NULL, -- Week 1-53, Month 1-12, Quarter 1-4
    
    status insight_status NOT NULL DEFAULT 'pending',
    
    selected_metrics JSONB,
    
    all_metrics JSONB,
    
    anomalies JSONB,
    
    expense_anomalies JSONB,
    
    milestones JSONB,
    
    activity JSONB,
    
    currency VARCHAR(3) NOT NULL,
    
    content JSONB,
    
    audio_path TEXT,
    
    generated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX insights_team_period_unique 
    ON insights(team_id, period_type, period_year, period_number);

CREATE INDEX insights_team_id_idx ON insights(team_id);

CREATE INDEX insights_team_period_type_idx 
    ON insights(team_id, period_type, generated_at DESC);

CREATE INDEX insights_status_idx ON insights(status);

ALTER TABLE insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team members can view their insights" ON insights
    FOR SELECT
    TO public
    USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "System can insert insights" ON insights
    FOR INSERT
    TO service_role
    WITH CHECK (true);

CREATE POLICY "System can update insights" ON insights
    FOR UPDATE
    TO service_role
    USING (true);

CREATE TABLE insight_user_status (
    insight_id UUID NOT NULL REFERENCES insights(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE,
    dismissed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY (insight_id, user_id)
);

CREATE INDEX insight_user_status_user_idx ON insight_user_status(user_id);

CREATE INDEX insight_user_status_insight_idx ON insight_user_status(insight_id);

CREATE INDEX insight_user_status_user_dismissed_idx 
    ON insight_user_status(user_id, dismissed_at) 
    WHERE dismissed_at IS NOT NULL;

CREATE INDEX insight_user_status_unread_idx 
    ON insight_user_status(user_id, insight_id) 
    WHERE read_at IS NULL;

ALTER TABLE insight_user_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own insight status" ON insight_user_status
    FOR SELECT
    TO public
    USING (user_id = auth.uid());

CREATE POLICY "Users can insert their own insight status" ON insight_user_status
    FOR INSERT
    TO public
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update their own insight status" ON insight_user_status
    FOR UPDATE
    TO public
    USING (user_id = auth.uid());

COMMENT ON TABLE insights IS 'AI-generated periodic business insights for teams';

COMMENT ON TABLE insight_user_status IS 'Per-user read and dismiss tracking for insights';

ALTER TABLE insights
ADD COLUMN title TEXT;

CREATE POLICY "Insights can be selected by a member of the team" ON insights
    FOR SELECT
    TO public
    USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

ALTER TABLE insights ADD COLUMN predictions jsonb;

CREATE TYPE platform_provider AS ENUM ('slack', 'telegram', 'whatsapp', 'sendblue');

CREATE TABLE platform_identities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  provider platform_provider NOT NULL,
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  external_user_id text NOT NULL,
  external_team_id text NOT NULL DEFAULT '',
  external_channel_id text,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT platform_identities_team_id_fkey
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT platform_identities_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT platform_identities_provider_external_unique
    UNIQUE (provider, external_team_id, external_user_id)
);

CREATE INDEX platform_identities_provider_external_idx
  ON platform_identities (provider, external_team_id, external_user_id);

CREATE INDEX platform_identities_team_id_idx
  ON platform_identities (team_id);

CREATE INDEX platform_identities_user_id_idx
  ON platform_identities (user_id);

ALTER TABLE platform_identities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Platform identities can be created by a member of the team"
  ON platform_identities
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform identities can be selected by a member of the team"
  ON platform_identities
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform identities can be updated by a member of the team"
  ON platform_identities
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform identities can be deleted by a member of the team"
  ON platform_identities
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE TABLE platform_link_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  code text NOT NULL,
  provider platform_provider NOT NULL,
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT platform_link_tokens_team_id_fkey
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT platform_link_tokens_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT platform_link_tokens_code_unique
    UNIQUE (code)
);

CREATE INDEX platform_link_tokens_code_idx
  ON platform_link_tokens (code);

CREATE INDEX platform_link_tokens_team_id_idx
  ON platform_link_tokens (team_id);

CREATE INDEX platform_link_tokens_user_id_idx
  ON platform_link_tokens (user_id);

ALTER TABLE platform_link_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Platform link tokens can be created by a member of the team"
  ON platform_link_tokens
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform link tokens can be selected by a member of the team"
  ON platform_link_tokens
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform link tokens can be updated by a member of the team"
  ON platform_link_tokens
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Platform link tokens can be deleted by a member of the team"
  ON platform_link_tokens
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE TABLE provider_notification_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  batch_key text NOT NULL,
  platform_identity_id uuid NOT NULL,
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  provider platform_provider NOT NULL,
  event_family text NOT NULL,
  payload jsonb NOT NULL,
  notification_context jsonb,
  window_ends_at timestamptz NOT NULL,
  sent_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT provider_notification_batches_identity_id_fkey
    FOREIGN KEY (platform_identity_id) REFERENCES platform_identities(id) ON DELETE CASCADE,
  CONSTRAINT provider_notification_batches_team_id_fkey
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT provider_notification_batches_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT provider_notification_batches_batch_key_unique
    UNIQUE (batch_key)
);

CREATE INDEX provider_notification_batches_due_idx
  ON provider_notification_batches (sent_at, window_ends_at);

CREATE INDEX provider_notification_batches_identity_idx
  ON provider_notification_batches (platform_identity_id);

CREATE INDEX provider_notification_batches_team_id_idx
  ON provider_notification_batches (team_id);

ALTER TABLE provider_notification_batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Provider notification batches can be created by a member of the team"
  ON provider_notification_batches
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Provider notification batches can be selected by a member of the team"
  ON provider_notification_batches
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Provider notification batches can be updated by a member of the team"
  ON provider_notification_batches
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));

CREATE POLICY "Provider notification batches can be deleted by a member of the team"
  ON provider_notification_batches
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (team_id IN (SELECT private.get_teams_for_authenticated_user()));
