#!/usr/bin/env python3
"""Extract the loadable subset of midday's real schema for a live PostgreSQL fixture.

``examples/brownfield/midday/schema.sql`` is a byte-for-byte concatenation of midday's 39
committed migrations. It does not load into an empty database: those migrations are increments
on top of a base schema that midday does not keep in ``packages/db/migrations`` (Supabase manages
it), so most statements reference tables, types, roles, and publications that are never created
there.

This script selects the statements that *are* self-contained once a Supabase runtime bridge is in
place, restricted to the six tables for which this migration corpus commits row-level-security
policies. Every kept statement is copied verbatim -- no SQL is rewritten, reordered, or
normalized. The dropped count is reported so the omission is visible rather than silent.

What is native (midday's own committed SQL, unmodified):
  - the CREATE TYPE, CREATE TABLE, CREATE INDEX, ALTER TABLE ... ENABLE ROW LEVEL SECURITY, and
    CREATE POLICY statements for all six tables with committed policies.

What is NOT here (see live_db/supabase_runtime.sql, which is synthesized and labeled as such):
  - the base tables those three reference (teams, users, customers, invoice_templates),
  - the Supabase roles and the auth/private functions the real policies call.

Usage:
    uv run python examples/brownfield/midday/scripts/brownfield-midday-live-schema.py
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# Every table for which the frozen migration corpus commits CREATE POLICY statements.
IN_SCOPE_TABLES = (
    "insights",
    "insight_user_status",
    "invoice_recurring",
    "platform_identities",
    "platform_link_tokens",
    "provider_notification_batches",
)

# Enum types the in-scope CREATE TABLE statements depend on.
IN_SCOPE_TYPES = (
    "insight_period_type",
    "insight_status",
    "invoice_recurring_frequency",
    "invoice_recurring_end_type",
    "invoice_recurring_status",
    "platform_provider",
)

HEADER = """\
-- GENERATED by examples/brownfield/midday/scripts/brownfield-midday-live-schema.py
-- DO NOT EDIT. Regenerate instead.
--
-- Every statement below is midday's own committed SQL, copied verbatim from
-- examples/brownfield/midday/schema.sql (itself a byte-for-byte concatenation of
-- packages/db/migrations/*.sql). Nothing here is rewritten or synthesized.
--
-- Load live_db/supabase_runtime.sql BEFORE this file: these statements reference base tables,
-- roles, and auth/private functions that midday does not commit in packages/db/migrations.
"""


def split_statements(sql: str) -> list[str]:
    """Split on semicolons that terminate a statement, ignoring comments and string literals."""
    statements: list[str] = []
    buf: list[str] = []
    i = 0
    in_line_comment = False
    in_block_comment = False
    in_string = False
    in_dollar: str | None = None
    while i < len(sql):
        ch = sql[i]
        two = sql[i : i + 2]
        if in_line_comment:
            if ch == "\n":
                in_line_comment = False
            buf.append(ch)
            i += 1
            continue
        if in_block_comment:
            if two == "*/":
                in_block_comment = False
                buf.append(two)
                i += 2
                continue
            buf.append(ch)
            i += 1
            continue
        if in_dollar is not None:
            if sql.startswith(in_dollar, i):
                buf.append(in_dollar)
                i += len(in_dollar)
                in_dollar = None
                continue
            buf.append(ch)
            i += 1
            continue
        if in_string:
            if ch == "'":
                in_string = False
            buf.append(ch)
            i += 1
            continue
        if two == "--":
            in_line_comment = True
            buf.append(two)
            i += 2
            continue
        if two == "/*":
            in_block_comment = True
            buf.append(two)
            i += 2
            continue
        if ch == "'":
            in_string = True
            buf.append(ch)
            i += 1
            continue
        dollar = re.match(r"\$[a-zA-Z_]*\$", sql[i:])
        if dollar is not None:
            in_dollar = dollar.group(0)
            buf.append(in_dollar)
            i += len(in_dollar)
            continue
        if ch == ";":
            buf.append(ch)
            statements.append("".join(buf).strip())
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return [s for s in statements if strip_comments(s)]


def strip_comments(statement: str) -> str:
    without_block = re.sub(r"/\*.*?\*/", " ", statement, flags=re.DOTALL)
    lines = [ln for ln in without_block.splitlines() if not ln.strip().startswith("--")]
    return "\n".join(lines).strip()


TARGET_PATTERNS = (
    r"create table(?: if not exists)?\s+\"?(?P<t>[a-z_]+)\"?",
    r"create(?: unique)? index(?: concurrently)?(?: if not exists)?"
    r"\s+\"?[a-z_]+\"?\s+on\s+\"?(?P<t>[a-z_]+)\"?",
    r"alter table(?: if exists)?(?: only)?\s+\"?(?P<t>[a-z_]+)\"?",
    r"create policy\s+(?:\"[^\"]+\"|[a-z_]+)\s+on\s+\"?(?P<t>[a-z_]+)\"?",
    r"comment on table\s+\"?(?P<t>[a-z_]+)\"?",
)

# Base tables the in-scope statements may reference by foreign key. supabase_runtime.sql
# creates these, so a reference to one is not an out-of-scope dependency.
BRIDGED_TABLES = ("teams", "users", "customers", "invoice_templates", "users_on_team")


def target_table(lowered: str) -> str | None:
    for pattern in TARGET_PATTERNS:
        match = re.match(pattern, lowered, re.DOTALL)
        if match is not None:
            return match.group("t")
    return None


def references_only_in_scope(statement: str) -> bool:
    """Keep a statement when it targets an in-scope table or type and nothing out of scope."""
    lowered = strip_comments(statement).lower()

    if lowered.startswith("create type"):
        return any(re.match(rf"create type\s+\"?{t}\"?\b", lowered) for t in IN_SCOPE_TYPES)

    # Match on the statement's own target, not on any table name appearing anywhere in it:
    # `ALTER TABLE invoices ... REFERENCES invoice_recurring(id)` targets an out-of-scope table.
    target = target_table(lowered)
    if target not in IN_SCOPE_TABLES:
        return False

    known = set(IN_SCOPE_TABLES) | set(BRIDGED_TABLES)
    referenced = set(re.findall(r"\breferences\s+\"?([a-z_]+)\"?", lowered))
    return referenced <= known


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--schema", type=Path, default=root / "schema.sql")
    parser.add_argument("--out", type=Path, default=root / "live_db" / "schema_scoped.sql")
    args = parser.parse_args()

    statements = split_statements(args.schema.read_text(encoding="utf-8"))
    kept = [s for s in statements if references_only_in_scope(s)]
    policies = [s for s in kept if strip_comments(s).lower().startswith("create policy")]
    tables = [s for s in kept if strip_comments(s).lower().startswith("create table")]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = "\n\n".join(strip_comments(s) for s in kept)
    args.out.write_text(f"{HEADER}\n{body}\n")

    print(
        f"statements: {len(statements)} parsed, {len(kept)} kept, "
        f"{len(statements) - len(kept)} dropped as out of scope\n"
        f"kept: {len(tables)} CREATE TABLE, {len(policies)} CREATE POLICY\n"
        f"out: {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
